{
 "title": "KPI",
 "time": {
  "from": "now-24h",
  "now": true,
  "to": "now"
 },
 "panels": [
  {
   "title": "Raw Metrics/Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.Full-Resolution-Metrics-Written.count), -1), 0)"
    }
   ]
  },
  {
   "title": "Rollups_per_minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Rollup-Execution-Timer.count), -1), 0)"
    }
   ]
  },
  {
   "title": "http ingest rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.http.DefaultHandler.HTTP-response-sending-timer.count), -1), 0)"
    }
   ]
  },
  {
   "title": "Queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.outputs.handlers.RollupHandler.Get-metrics-from-db.count), -1), 0)"
    }
   ]
  },
  {
   "title": "Http ingest latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p999, -1), 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p99, -1), 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p95, -1), 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.mean, -1), 10)), -1)"
    }
   ]
  },
  {
   "title": "Rollup Wait time p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Rollup-Wait-Histogram.p95, -1), 0)"
    }
   ]
  }
 ]
}