{
 "title": "Blueflood Ops",
 "time": {
  "from": "now-12h",
  "now": true,
  "to": "now"
 },
 "panels": [
  { "title": "Ingestion Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raw Metrics/Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(groupByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.Full-Resolution-*Metrics-Written.count), -1), 0, 'sumSeries'), 0)"
    }
   ]
  },
  {
   "title": "http ingest rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.http.DefaultHandler.HTTP-response-sending-timer.count), -1), 0)"
    }
   ]
  },
  { "title": "Delay Metrics Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Short delay metrics/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.Metrics-with-short-delay-received.count), -1), 0)"
    }
   ]
  },
  {
   "title": "Long delay metrics/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.Metrics-with-long-delay-received.count), -1), 0)"
    }
   ]
  },
  { "title": "Ingestion Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ingest Latency averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p999, 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p99, 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.p95, 10)), -1)"
    },
    {
     "target": "aliasByNode(averageSeries(averageSeriesWithWildcards(blueflood-minikube.com.rackspacecloud.blueflood.inputs.handlers.HttpMetricsIngestionHandler.*.mean, 10)), -1)"
    }
   ]
  },
  {
   "title": "Write duration (Ingestion) in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.inputs.processors.BatchWriter.Write-Duration.{mean,p95,p999},-1),0,-1)"
    }
   ]
  },
  { "title": "Rollup Rate and Queued", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Rollups_per_minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Rollup-Execution-Timer.count), -1), 0)"
    }
   ]
  },
  {
   "title": "Queued Rollups by Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Queued-Rollup-Count, -1), 0)"
    }
   ]
  },
  { "title": "Rollup execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Rollup Wait time p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Rollup-Wait-Histogram.p95, -1), 0)"
    }
   ]
  },
  {
   "title": "Rollup execution timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Rollup-Execution-Timer.{mean,p95,p99},-1),0,-1)"
    }
   ]
  },
  { "title": "Rollup Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Re-roll slot due to delayed metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.5m-Re-rolling-up-because-of-delayed-metrics.count), 0, 3)"
    }
   ]
  },
  {
   "title": "Scheduled-Slot-Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.service.RollupService.Scheduled-Slot-Check,-1),0)"
    }
   ]
  },
  { "title": "Repose Status codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Repose 5xx responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(*.iad.prod.bf.k1k.me-org.openrepose.core.ResponseCode.Repose.5XX.count), 0)"
    }
   ]
  },
  {
   "title": "Blueflood 5xx reponses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(*.iad.prod.bf.k1k.me-org.openrepose.core.ResponseCode.localhost:*.5XX.count), 0)"
    }
   ]
  },
  { "title": "Query rate and search duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.outputs.handlers.RollupHandler.Get-metrics-from-db.count),-1),0)"
    }
   ]
  },
  {
   "title": "ElasticIO Query Search Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticIO.Search-Duration.count),-1)),'rate')"
    },
    {
     "target": "aliasByNode(averageSeriesWithWildcards(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticIO.Search-Duration.{p999,p95,mean},0),-1)"
    }
   ]
  },
  { "title": "ElasticIO Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "ES DiscoveryWriter Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticIO.Write-Duration.{p999,p95,mean},-1),0),-1)"
    }
   ]
  },
  {
   "title": "ES DiscoveryWriter Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticIO.Write-Duration.count),-1),0)"
    }
   ]
  },
  { "title": "ElasticTokensIO Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "ES TokenDiscoveryWriter Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticTokensIO.Write-Duration.{p999,p95,mean}, -1), 0), -1)"
    }
   ]
  },
  {
   "title": "ES TokenDiscoveryWriter Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.ElasticTokensIO.Write-Duration.count), -1), 0)"
    }
   ]
  },
  { "title": "Cache Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "LocatorCache locator count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(blueflood-minikube.com.rackspacecloud.blueflood.cache.LocatorCache.Current-Locators-Count, 0)"
    }
   ]
  },
  {
   "title": "LocatorCache delayed locator count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(blueflood-minikube.com.rackspacecloud.blueflood.cache.LocatorCache.Current-Delayed-Locators-Count, 0)"
    }
   ]
  },
  {
   "title": "TokenCache token count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(blueflood-minikube.com.rackspacecloud.blueflood.cache.TokenCache.Current-Tokens-Count, 0)"
    }
   ]
  },
  { "title": "Blueflood Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Blueflood Ops/min overall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.InstrumentedConnectionPoolMonitor.Operation-Result-Success.count)), 'success')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.InstrumentedConnectionPoolMonitor.Operation-Result-Failure.count)), 'fail')"
    }
   ]
  },
  {
   "title": "Blueflood Ops/min (by node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.InstrumentedConnectionPoolMonitor.Connection-Borrowed.count), -1), 0, 3)"
    }
   ]
  },
  { "title": "Cassandra requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Cassandra reads/minute by CF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(nonNegativeDerivative(*.*.cassandra.org.apache.cassandra.metrics.ColumnFamily.DATA.*.ReadLatency.count),9,'sum')"
    }
   ]
  },
  {
   "title": "Cassandra writes/minute by CF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(nonNegativeDerivative(*.*.cassandra.org.apache.cassandra.metrics.ColumnFamily.DATA.*.WriteLatency.count),9,'sum')"
    }
   ]
  },
  { "title": "Cassandra Connection Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "All Pools Exhausted (Cassandra connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.All-Pools-Exhausted.m1_rate, 0, 3)"
    }
   ]
  },
  {
   "title": "Exceptions-Pool-Exhausted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(blueflood-minikube.com.rackspacecloud.blueflood.io.InstrumentedConnectionPoolMonitor.Exceptions-Pool-Exhausted.m1_rate,0,3)"
    }
   ]
  },
  { "title": "Cass read and write errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "cassandra write errors/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.writes.*Error*.count), 10), 0)"
    }
   ]
  },
  {
   "title": "cassandra read errors/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(nonNegativeDerivative(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.reads.*Error*.count), 10), 0)"
    }
   ]
  },
  { "title": "Metrics full latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Metrics_full read latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "averageSeriesWithWildcards(groupByNode(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.reads.metrics_full.{p999,p99,p95,mean}, -1, 'avg'), 3)"
    }
   ]
  },
  {
   "title": "metrics_full writes mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "groupByNode(maximumAbove(blueflood-minikube.com.rackspacecloud.blueflood.io.Instrumentation.writes.metrics_full.{p999,p99,p95,mean}, -1), -1, 'maxSeries')"
    }
   ]
  },
  { "title": "Repose Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Repose 2xx responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(*.iad.prod.bf.k1k.me-org.openrepose.core.ResponseCode.Repose.2XX.count), 0, 10)"
    }
   ]
  },
  {
   "title": "Repose 4xx responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(*.iad.prod.bf.k1k.me-org.openrepose.core.ResponseCode.Repose.4XX.count), 0, 10)"
    }
   ]
  }
 ]
}