#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

METRIC_UNITS_MAP = {
  "remote.dns" : {
    "answer" : {
      "unit" : "ips",
      "description" : "",
    },
    "rtt" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "ttl" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.tcp" : {
    "banner" : {
      "unit" : "unknown",
      "description" : "",
    },
    "banner_match" : {
      "unit" : "unknown",
      "description" : "",
    },
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.ftp-banner" : {
    "banner" : {
      "unit" : "unknown",
      "description" : "",
    },
    "banner_match" : {
      "unit" : "unknown",
      "description" : "",
    },
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.imap-banner" : {
    "banner" : {
      "unit" : "unknown",
      "description" : "",
    },
    "banner_match" : {
      "unit" : "unknown",
      "description" : "",
    },
    "body_match" : {
      "unit" : "unknown",
      "description" : "",
    },
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_body" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.mssql-banner" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.mysql-banner" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.pop3-banner" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.postgresql-banner" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.telnet-banner" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.http" : {
    "bytes" : {
      "unit" : "bytes",
      "description" : "",
    },
    "cert_end" : {
      "unit" : "timestamp_seconds",
      "description" : "",
    },
    "cert_end_in" : {
      "unit" : "seconds",
      "description" : "",
    },
    "cert_start" : {
      "unit" : "timestamp_seconds",
      "description" : "",
    },
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "truncated" : {
      "unit" : "bytes",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.smtp-banner" : {
    "bytes" : {
      "unit" : "bytes",
      "description" : "",
    },
    "cert_end" : {
      "unit" : "timestamp_seconds",
      "description" : "",
    },
    "cert_end_in" : {
      "unit" : "seconds",
      "description" : "",
    },
    "cert_start" : {
      "unit" : "timestamp_seconds",
      "description" : "",
    },
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "truncated" : {
      "unit" : "bytes",
      "description" : "",
    },
    "tt_connect" : {
      "unit" : "milliseconds",
      "description" : "",
    },
    "tt_firstbyte" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
  "remote.ping" : {
    "available" : {
      "unit" : "percent",
      "description" : "",
    },
    "average" : {
      "unit" : "seconds",
      "description" : "",
    },
    "maximum" : {
      "unit" : "seconds",
      "description" : "",
    },
    "minimum" : {
      "unit" : "seconds",
      "description" : "",
    },
    "count" : {
      "unit" : "other",
      "description" : "",
    },
  },
  "remote.ssh" : {
    "duration" : {
      "unit" : "milliseconds",
      "description" : "",
    },
  },
}
UNIT_ENUM_REVERSE_MAP = {
  "unknown" :   0,
  "bits" :   2,
  "bytes" :   3,
  "kilobytes" :   4,
  "megabytes" :   5,
  "milliseconds" :   6,
  "seconds" :   7,
  "timestamp_milliseconds" :   8,
  "timestamp_seconds" :   9,
  "percent" :   10,
}
