server:
  applicationConnectors:
    - type: http
      bindHost: 127.0.0.1
      port: 19010
  adminConnectors:
    - type: http
      bindHost: 127.0.0.1
      port: 19011
cassandraHosts: ["127.0.0.1:19180", "127.0.0.1:19180"]
rollupKeyspace: data
  