name: "Validate and plan"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Configure git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Build and test
        run: |
          mvn clean install -Dmaven.javadoc.skip --quiet
          mvn jacoco:report jacoco:report-integration
          mvn package -P all-modules -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip
#      - name: Generate changelog
#        id: changelog
#        uses: metcalfc/changelog-generator@v0.4.4
#        with:
#          myToken: ${{ secrets.GITHUB_TOKEN }}
#      - name: Create GitHub Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: latest
#          body: |
#            ### Things that changed in this release
#            ${{ steps.changelog.outputs.changelog }}
#          draft: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            */target/site
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            blueflood-all/target/blueflood-all-*-jar-with-dependencies.jar
