name: "Create PR on release"
on:
  push:
    branches:
      - release/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: rohit/test-cli
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "Updated pom versions to next developement version"

# on:
#   create:
#     branches:
#     - release/*

# jobs:
#   pull-request:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: pull-request
#       uses: repo-sync/pull-request@v2
#       with:
#         destination_branch: "master"
#         github_token: ${{ secrets.GITHUB_TOKEN }}
